<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Validasi Permit</title><style>body{font-family:Arial,sans-serif;background:#eef3f7;color:#182536;margin:0}.wrap{max-width:680px;margin:40px auto;padding:20px}.card{background:#fff;border-radius:14px;padding:28px;box-shadow:0 8px 30px #1c34451c}.ok{border-top:8px solid #159447}.bad{border-top:8px solid #c62828}.badge{display:inline-block;padding:6px 12px;border-radius:99px;background:#e7edf2;font-weight:bold}.active{background:#dff5e7;color:#087232}.danger{background:#fde3e3;color:#a51111}dt{font-size:12px;color:#667; margin-top:15px}dd{margin:3px 0;font-weight:bold}.notice{padding:12px;border-radius:8px;background:#eef8f1;margin:18px 0}.warn{background:#fdeaea;color:#8d1111}</style></head><body><main class="wrap"><div class="card {{ $validClaim ? 'ok' : 'bad' }}">
<h1>Validasi Mine Permit</h1>
@if($validClaim)<div class="notice"><strong>Valid — pengajuan ini disetujui KTT pada {{ \Illuminate\Support\Carbon::parse($claim['approved_at'])->timezone(config('app.timezone'))->format('d-m-Y H:i') }}.</strong></div>@else<div class="notice warn"><strong>Tidak valid — bukti persetujuan KTT gagal diverifikasi.</strong></div>@endif
<p><span class="badge {{ $issuance->status === 'active' && !$issuance->expires_at->isPast() ? 'active' : 'danger' }}">{{ strtoupper($issuance->expires_at->isPast() && $issuance->status === 'active' ? 'expired' : $issuance->status) }}</span></p>
<dl><dt>Nama</dt><dd>{{ data_get($snapshot, 'manpower.name') }}</dd><dt>Perusahaan</dt><dd>{{ data_get($snapshot, 'manpower.partner_name') }}</dd><dt>Nomor Mine Permit</dt><dd>{{ $issuance->mine_permit_number }}</dd>@if($issuance->simpol_number)<dt>Nomor SIMPOL</dt><dd>{{ $issuance->simpol_number }}</dd>@endif<dt>Masa berlaku</dt><dd>{{ $issuance->valid_from->format('d-m-Y') }} s.d. {{ $issuance->expires_at->format('d-m-Y') }}</dd><dt>Area akses</dt><dd>{{ collect($snapshot['access_areas'] ?? [])->join(', ') ?: '-' }}</dd>@if($issuance->simpol_number)<dt>Kategori SIMPER</dt><dd>{{ collect($snapshot['categories'] ?? [])->map(fn($item) => $item['name'].' — '.$item['level'])->join(', ') }}</dd>@endif</dl>
@if($issuance->status === 'revoked')<div class="notice warn">Permit ini telah dicabut dan tidak boleh digunakan.</div>@endif
<p style="font-size:12px;color:#667;margin-top:24px">Halaman sistem ini adalah sumber status resmi. Data pribadi dan dokumen pengajuan tidak ditampilkan.</p>
</div></main></body></html>
